name: 'Image: KlipperScreen'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  build:
    uses: wiwa5607/my-prind/.github/workflows/image-workflow.yaml@main
    with:
      app: klipperscreen
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
